name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm run build
    - name: Create deployment artifact
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: tar -czf "${GITHUB_SHA}.tar.gz" --exclude=*.git --exclude=node_modules *
    - name: Store artifact for distribution
      uses: actions/upload-artifact@v2
      with:
        name: app-build
        path: ${{ github.sha }}.tar.gz
  
  prepare-release-on-server:
    name: Sync application to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: app-build
      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          source: ${{ github.sha }}.tar.gz
          target: sites/rickycierny.com/artifacts
      - name: Extract archive and create directories
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          envs: GITHUB_SHA
          script: |
            mkdir -p "sites/rickycierny.com/releases/${GITHUB_SHA}"
            tar xzf sites/rickycierny.com/artifacts/${GITHUB_SHA}.tar.gz -C "sites/rickycierny.com/releases/${GITHUB_SHA}"
  activate-release:
    name: Activate release
    runs-on: ubuntu-latest
    needs: [build, prepare-release-on-server]
    steps:
      - name: Activate release
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: sites/rickycierny.com/releases/${{ github.sha }}
          ACTIVATE_RELEASE_PATH: sites/rickycierny.com/current
          SHARED_PATH: sites/rickycierny.com/shared
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          envs: GITHUB_SHA,RELEASE_PATH,ACTIVATE_RELEASE_PATH,SHARED_PATH
          script: |
            rm -rf $ACTIVATE_RELEASE_PATH
            ln -sr $RELEASE_PATH $ACTIVATE_RELEASE_PATH
            ln -snfrv "${SHARED_PATH}/assets" "${RELEASE_PATH}/public/assets"
  clean-up:
    name: Clean up
    runs-on: ubuntu-latest
    needs: [build, prepare-release-on-server, activate-release]
    steps:
      - name: Run after hooks
        uses: appleboy/ssh-action@master
        env:
          RELEASES_PATH: sites/rickycierny.com/releases/
          ARTIFACTS_PATH: sites/rickycierny.com/artifacts/
          RELEASE_PATH: sites/rickycierny.com/releases/${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          envs: RELEASES_PATH,ARTIFACTS_PATH,RELEASE_PATH
          script: |
            cd $RELEASES_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
            cd ~
            cd $ARTIFACTS_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
